  0%|                                                                                                                                                                                                                                                       | 0/3 [00:00<?, ?it/s]INFO:root:training epoch 1
INFO:root:evaluating epoch 1
2022-10-27 15:03:39,194 - root - INFO - training epoch 1
2022-10-27 15:03:39,194 - root - INFO - evaluating epoch 1
INFO:root:eval logs:
accuracy: 0.008219177834689617
loss: 5.851645469665527
INFO:root:saving checkpoint
2022-10-27 15:04:56,403 - root - INFO - eval logs:
accuracy: 0.008219177834689617
loss: 5.851645469665527
2022-10-27 15:04:56,416 - root - INFO - saving checkpoint
INFO:root:testing
  0%|                                                                                                                                                                                                                                                       | 0/3 [01:18<?, ?it/s]
Traceback (most recent call last):
  File "/home/alex_ch/flax_env/lib/python3.9/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/alex_ch/flax_env/lib/python3.9/site-packages/wandb/apis/public.py", line 937, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/home/alex_ch/flax_env/lib/python3.9/site-packages/wandb/apis/public.py", line 4151, in __init__
    self._load()
  File "/home/alex_ch/flax_env/lib/python3.9/site-packages/wandb/apis/public.py", line 4735, in _load
    raise ValueError(
ValueError: Project alexunderch/training ViT with flax does not contain artifact: "amber-sun-74-checkpoint:latest"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/alex_ch/Documents/flax_vit/vit/nn/train_main.py", line 150, in full_trainining
    restored_best_state = restore_checkpoint_wandb("ckpt_file.pth", restored_best_state)
  File "/home/alex_ch/Documents/flax_vit/vit/nn/common_utils.py", line 56, in restore_checkpoint_wandb
    artifact = wandb.use_artifact(
  File "/home/alex_ch/flax_env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 255, in wrapper
    return func(self, *args, **kwargs)
  File "/home/alex_ch/flax_env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2575, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "/home/alex_ch/flax_env/lib/python3.9/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/alex_ch/flax_env/lib/python3.9/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/alex_ch/flax_env/lib/python3.9/site-packages/wandb/apis/public.py", line 937, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/home/alex_ch/flax_env/lib/python3.9/site-packages/wandb/apis/public.py", line 4151, in __init__
    self._load()
  File "/home/alex_ch/flax_env/lib/python3.9/site-packages/wandb/apis/public.py", line 4735, in _load
    raise ValueError(
wandb.errors.CommError: Project alexunderch/training ViT with flax does not contain artifact: "amber-sun-74-checkpoint:latest"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/alex_ch/Documents/flax_vit/vit/nn/test_training.py", line 130, in <module>
    test_full_training()
  File "/home/alex_ch/Documents/flax_vit/vit/nn/test_training.py", line 121, in test_full_training
    full_trainining(
  File "/home/alex_ch/Documents/flax_vit/vit/nn/train_main.py", line 152, in full_trainining
    restored_best_state = TrainState(step = eval_state.step,
TypeError: __init__() missing 1 required positional argument: 'opt_state'
2022-10-27 15:04:57,618 - root - INFO - testing